spring.application.name=Mini_Project

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false

spring.thymeleaf.cache=false

groq.api-key= Your_API_Key
groq.model=llama-3.3-70b-versatile

youtube.api.key= Your_Youtube_API_Key

spring.datasource.url=jdbc:postgresql://localhost:5432/roadmapdb
spring.datasource.username=postgres
spring.datasource.password=database24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
